apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-app
  namespace: gitops-app
  labels:
    app: gitops-app
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: gitops-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: gitops-app
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: gitops-app
          image: ghcr.io/2d-jack/gitops-demo:3a46465
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              name: http
          env:
            - name: APP_VERSION
              value: "1.0.0"  # APP_VERSION
            - name: ENVIRONMENT
              value: "production"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
